# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: ':catalog:jacocoTestReport'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '**/jacocoTestReport.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/catalog/java'
    reportDirectory: '$(System.DefaultWorkingDirectory)/build/coverage-report'
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/catalog/build'
    Contents: |
      outputs/apk/release/*.apk
      outputs/apk/release/*.json
    TargetFolder: '$(build.artifactStagingDirectory)/material-catalog'
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/material-theme-builder/build'
    Contents: |
      outputs/apk/release/*.apk
      outputs/apk/release/*.json
    TargetFolder: '$(build.artifactStagingDirectory)/material-builder'
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: GitHubRelease@1
  enabled: false
  inputs:
    gitHubConnection: 'github connection 1'
    repositoryName: 'jstefanowski/material-components-android'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'v*.*.*'
    title: 'Test release title'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'Example release notes'
    assets: '$(build.artifactStagingDirectory)/**/*.apk'
    addChangeLog: false
- task: UniversalPackages@0
  enabled: false
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '4c541e37-6c7d-4866-a4a2-d7f2afe16e1b/dbbdfd75-d72b-4e5f-8cba-ce9e83bd1537'
    vstsFeedPackagePublish: 'test_pck_name'
    versionOption: 'patch'