# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      curl https://rclone.org/install.sh | sudo bash
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: ':catalog:jacocoTestReport'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '**/jacocoTestReport.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/catalog/java'
    reportDirectory: '$(System.DefaultWorkingDirectory)/build/coverage-report'